### ISSUE TITLE
Figure captions

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-openrefine-guide#11]
Figures in this guide are -mostly- software screenshots. I don't think making captions for every image makes a lot of sense in these somewhat tech-documents, and so I'm inclined not to make captions. But there might be some reason why we would really want them...?
@kcopas what do you think?

**Comment by kcopas** [comment]
I don't think we need them. Might be a worth adding it as an explicit question for peer reviewers, tho…

Leaving the issue open in order not to lose that thought.

**Comment by pzermoglio** [comment]
We will keep figures without captions for simplicity and to avoid redundancies all over. Closing this issue.
