### ISSUE TITLE
Installation links out of date

### ISSUE THREAD

**Issue by MattBlissett** [gbif/doc-openrefine-guide#15]
[Apéndice 1: instalación de OpenRefine](https://docs.gbif-uat.org/openrefine-guide/1.0/es/#app-a).

Installation instructions go out of date -- Java 6 and Java 7 are no longer supported, so that reference makes little sense, and the links to the zip files are for version 3.1, not the current 3.3.  The OpenRefine site doesn't ([yet!](https://github.com/OpenRefine/openrefine.github.com/issues/56)) have Spanish installation/download instructions, otherwise we could just link there.

https://github.com/OpenRefine/OpenRefine/releases/latest links to the latest release page, but not the  release zipfile itself.

I'm not sure what the best solution is.

**Comment by kcopas** [comment]
@pzermoglio could you have a look at this? 

We really are about to get this train out of the station.

**Comment by pzermoglio** [comment]
Apéndice updated. 
Including now notes about possibility of installing extensions.
Closing issue.
