### ISSUE TITLE
Add CROME browser as the recommended app to open OR

### ISSUE THREAD

**Issue by camiplata** [gbif/doc-openrefine-guide#17]
Sección 1 Paso 1. http://mb.gbif.org/documents/doc-openrefine-guide/es/#_carga_de_datos_y_creaci%C3%B3n_de_un_proyecto

es
En la sección de 'Carga de datos y creación de un proyecto' se recomienda añadir CHROME como el navegador de preferencia, tras utilizar Open refine en múltiples talleres hemos notado problemas al abrirlo en Internet explorer (el menos recomendado), safari (medianamente recomendado)y FireFox (problemas intermitentes). Aunque funciona en dichos navegadores al utilizar funciones más complejas o hacer cruces de información, empieza a fallar o se pierden pasos. 

en- summarized
We have had regular to bad experiences using Open Refine with Internet explorer, safari y FireFox in several workshops, the most stable is CHROME, specially for the advance task  and for using GREL expressions,

**Comment by pzermoglio** [comment]
es
De acuerdo, agregado en Paso 1:
"Si bien puede ejecutar el programa utilizando cualquier navegador, nuestra recomendación es que utilice Google Chrome, pues otros navegadores suelen presentar diversos problemas, sobre todo cuando se intentan utilizar funciones más complejas."

en
Agreed, added in Paso 1 (Step 1).

Closing issue.
