### ISSUE TITLE
Contribution of extra contents for advance use of Open Refine  for biodiversity data validation

### ISSUE THREAD

**Issue by camiplata** [gbif/doc-openrefine-guide#18]
SiB Colombia's team has worked with OpenRefine for several years, thus we have developed two OR step by step guides for basic and advance  biodiversity data management in DwC. We will like to contribute to the current guide with the contents we already have, particularly with the advance use guide, where we offer Open Refine scritps for data validation using several tools of the GBIF community

Guides
1. http://repository.humboldt.org.co/handle/20.500.11761/35348
2. http://repository.humboldt.org.co/handle/20.500.11761/35350
Scripts-  https://github.com/SIB-Colombia/data-quality-open-refine

SiB Colombia's guides have been authored by @RicardoOrtizG @leobuitrago and myself

**Comment by pzermoglio** [comment]
Content added by @camiplata as Section 5. Most excellent additions to the Guide! Thanks @camiplata and team!
Closing this issue.
