### ISSUE TITLE
Comentarios sobre Guía de Uso Básico de OpenRefine (ESP)

### ISSUE THREAD

**Issue by bienflorencia** [gbif/doc-openrefine-guide#20]
Me parece que está muy buena la guía, intuitiva y explicativa. Como reciente usuaria/exploradora de OpenRefine, me resultó útil para conocer algunas opciones que no tenía. No me dio para ver todo el documento (me faltó el punto 4), pero dejo mínimos comentarios/preguntas sobre las partes del documento que llegué a ver. 

https://docs.gbif-uat.org/openrefine-guide/1.0/es/#uso-de-facetas
El uso de facetas, ¿tiene efecto después sobre ediciones que no son necesariamente de esas facetas? ¿Hay algún problema con la memoria si se acumulan varias facetas? ¿Es conveniente eliminar las facetas luego de creadas y usadas? El documento es claro igual al mencionar que deben eliminarse si se quiere exportar.

https://docs.gbif-uat.org/openrefine-guide/1.0/es/#facetas-num%C3%A9ricas
Me surge una duda. Para hacer facetas de campos con números, ¿qué pasa si el campo tiene números pero no se transformó a tipo ‘numérico’? ¿pueden los campos ser de tipo texto y clasificarse igual con facetas numéricas? Entiendo que sí, pero ¿cuál es la mejor práctica? Quizás se puede aprovechar acá para mostrar cómo transformar el tipo de dato que usa la columna.

https://docs.gbif-uat.org/openrefine-guide/1.0/es/#n%C3%BAmero-de-elecciones-l%C3%ADmite-en-las-facetas
Le llamaría ‘Límite en el número de elecciones de las Facetas’

https://docs.gbif-uat.org/openrefine-guide/1.0/es/#filtros-simples
Al final de esta sección se puede agregar una aclaración/adevertencia sobre que si se usaron esos campos para concatenar en uno nuevo, el/la usuarix debe de hacer un ‘refresh’ para que los nuevos valores se actualicen también porque no son dinámicos.

https://docs.gbif-uat.org/openrefine-guide/1.0/es/#agrupamientos-simples
Buenísimo el ejemplo con el orden de los colectores A y B. 

https://docs.gbif-uat.org/openrefine-guide/1.0/es/#deshacer-pasos
En la primera lectura este ejemplo me resultó que estaba un poco complejo. Los pasos están enganchados ¿cierto? O sea que, si en una serie de 5 pasos le erramos en el segundo y queremos ‘dejarlo sin efecto’, tenemos que volver hasta ese paso en teoría perdiendo los que le siguen, el 3, 4 y 5. Al volver a un estado previo y corregir nuestro error en el paso 2, necesariamente vamos a tener que rehacer los pasos siguientes. Sin embargo, esos pasos se van a perder (si no los guardamos) y por eso si queremos volver a ejecutarlos y se tratan de procesos complejos es importante guardarlos.

Por ahí mis comentarios. No son muchos porque me pareció muy bueno el doc!

**Comment by pzermoglio** [comment]
Muchas gracias Flor @bienflorencia por tus comentarios y sugerencias!!

> https://docs.gbif-uat.org/openrefine-guide/1.0/es/#uso-de-facetas
> El uso de facetas, ¿tiene efecto después sobre ediciones que no son necesariamente de esas facetas? ¿Hay algún problema con la memoria si se acumulan varias facetas? ¿Es conveniente eliminar las facetas luego de creadas y usadas? El documento es claro igual al mencionar que deben eliminarse si se quiere exportar.

Si hay valores seleccionados en una faceta, sólo se actúa sobre los registros que tienen esos valores, aunque la acción se ejecute sobre otro campo. Agregué una nota a este respecto, dentro de una nueva subsección: [2.2.3. Inclusión y exclusión de registros usando facetas](https://docs.gbif-uat.org/openrefine-guide/1.0/es/#inclusi%C3%B3n-y-exclusi%C3%B3n-de-registros-usando-facetas). Un indicador rápido que se puede usar para saber si hay algún valor seleccionado (aunque depende el caso no funciona), es el número de registros que se muestra en negrita arriba de la tabla. Típicamente, si hay valores seleccionados en alguna faceta, ese número será menor que el número total de filas de tu proyecto. 
Desde mi experiencia, siempre es bueno cerrar las facetas que no están en uso, por una cuestión de comodidad (se van apilando a la izquierda de la pantalla) y de seguridad (para evitar seleccionar algún valor inadvertidamente).

**Comment by pzermoglio** [comment]
>https://docs.gbif-uat.org/openrefine-guide/1.0/es/#facetas-num%C3%A9ricas
>Me surge una duda. Para hacer facetas de campos con números, ¿qué pasa si el campo tiene números pero no se transformó a tipo ‘numérico’? ¿pueden los campos ser de tipo texto y clasificarse igual con facetas numéricas? Entiendo que sí, pero ¿cuál es la mejor práctica? Quizás se puede aprovechar acá para mostrar cómo transformar el tipo de dato que usa la columna.

Muy buena pregunta @bienflorencia!

Si el campo no es de tipo número, la faceta numérica no te sirve, se ve así, por ejemplo en el campo "month", que tiene números pero en formato texto:
![image](https://user-images.githubusercontent.com/9394433/108600366-ab76f580-7375-11eb-9fb4-ed8f51ca7398.png)

Para transformar hay que seguir esta ruta:
![image](https://user-images.githubusercontent.com/9394433/108600393-db25fd80-7375-11eb-9856-4d5046ee1a84.png)

Y una vez que transformaste, entonces la faceta numérica sobre ese campo se ve así:
![image](https://user-images.githubusercontent.com/9394433/108600385-d103ff00-7375-11eb-8e8a-0790fc86ef08.png)

Agregué una nota de advertencia sobre esto y la ruta que debe seguirse para la transformación al final de la [sección 2.2.4](https://docs.gbif-uat.org/openrefine-guide/1.0/es/#facetas-num%C3%A9ricas).

**Comment by pzermoglio** [comment]
>https://docs.gbif-uat.org/openrefine-guide/1.0/es/#n%C3%BAmero-de-elecciones-l%C3%ADmite-en-las-facetas
>Le llamaría ‘Límite en el número de elecciones de las Facetas’

Cambiado, ver https://github.com/gbif/doc-openrefine-guide/issues/26

**Comment by pzermoglio** [comment]
All topics here addressed and relevant additions/changes incorporated to the Guide.
Closing issue.
