### ISSUE TITLE
Suggestion to re-locate example 2.1.

### ISSUE THREAD

**Issue by camiplata** [gbif/doc-openrefine-guide#21]
es
El ejemplo con el que inicia la [sección 2.1](http://mb.gbif.org/documents/doc-openrefine-guide/es/#_manejo_b%C3%A1sico_de_columnas) es bastante apropiado, sin embargo no es hasta la sección [2.1.3](http://mb.gbif.org/documents/doc-openrefine-guide/es/#_nuevas_columnas_a_partir_transformaciones_simples_de_otras_columnas) que realmente aplica el ejemplo. Considero que el ejemplo de contexto sería más útil al iniciar la sección 2.1.3.

en
Move example at the begin of  2.1 to 2.1.3. where it come more useful

**Comment by pzermoglio** [comment]
es
De acuerdo! Ejemplo movido al inicio de la sección 2.1.3.
en
Agreed! Example moved to the beginning of section 2.1.3.
