### ISSUE TITLE
For discussion,  ambiguous use of 'campo' and 'columna'

### ISSUE THREAD

**Issue by camiplata** [gbif/doc-openrefine-guide#22]
Las palabras _campo_ y _columna_ son usadas indistintamente, personalmente asocio la palabra _campo_ a lo que en excel se considera como _celda_, sin embargo desconozco cual sería el uso 'correcto' de estas dos palabras. 

Teniendo en cuenta que las opciones de Open Refine siempre hacen referencia  a columnas, creo que se le debería dar preferencia a la palabra _columna_ sobre _campo_ , esto para  dar mayor claridad para toda la comunidad hispanohablante, ya que pueden haber ligeras diferencias en la interpretación según el país.

**Comment by pzermoglio** [comment]
De acuerdo con que puede generar alguna confusión. Cuando se habla de DwC, se suele usar campo para denominar en realidad a columnas que llevan el nombre de un término, por eso es creo que está también un poco mezclado el uso y la interpretación campo/columna. 
Introduje una aclaración super simple en la sección [Cómo usar esta guía](https://docs.gbif-uat.org/openrefine-guide/1.0/es/#c%C3%B3mo-usar-esta-gu%C3%ADa):
"En la Guía se utilizan los términos ‘campo’ y ‘columna’ indistintamente."

@camiplata te parece que esto resolvería el asunto?

**Comment by camiplata** [comment]
Me parece una buena solución!
