### ISSUE TITLE
Addition of all dataset trim leading and trailing, and collapse withespace

### ISSUE THREAD

**Issue by camiplata** [gbif/doc-openrefine-guide#24]
En la  [sección 2.2.2.](http://mb.gbif.org/documents/doc-openrefine-guide/es/#_facetas_y_espacios_en_blanco) después de explicar la lógica y opciones de columna para limpiar espacios, se podría incluir la opción de  ejecutar ambas acciones sobre todo el conjunto de datos vía el comando `value.trim().replace(/\s+/,' ')`

**Comment by pzermoglio** [comment]
De acuerdo. Incluido en nueva subsección bajo 2.2.2.: Espacios en blanco extra en todo el conjunto de datos.

Closing issue.
