### ISSUE TITLE
Addition of options history and starred GREL expressions for text transform

### ISSUE THREAD

**Issue by camiplata** [gbif/doc-openrefine-guide#25]
El historial de expresiones y la opción de 'con estrella' facilita el re-uso de la expresiones en GREL para nuevos usuarios de OpenRefine
![image](https://user-images.githubusercontent.com/5700527/89488202-f8460680-d76c-11ea-99bf-396ad7b8b326.png)

**Comment by pzermoglio** [comment]
See also https://github.com/gbif/doc-openrefine-guide/issues/19

**Comment by pzermoglio** [comment]
Added new subsection [2.5.4. Reutilizar expresiones regulares](https://docs.gbif-uat.org/openrefine-guide/1.0/es/#reutilizar-expresiones-regulares).
Topic addressed, closing this issue.
