### ISSUE TITLE
Minor suggested additions or fixes

### ISSUE THREAD

**Issue by camiplata** [gbif/doc-openrefine-guide#26]
Other minor suggestions for you to consider if useful.
I didn't manage to do a complete/detailed review of the document before the deadline, I hope to contribute more latter.
Thank you for the great document @pzermoglio and @tucotuco, I learned some new things while reviewing the document 😃 

##### [Sección 1](http://mb.gbif.org/documents/doc-openrefine-guide/es/#_carga_de_datos_y_creaci%C3%B3n_de_un_proyecto) paso 2
Mencionar brevemente la posibilidad de usar tags para una mejor organización de los proyectos

##### [Sección 1](http://mb.gbif.org/documents/doc-openrefine-guide/es/#_carga_de_datos_y_creaci%C3%B3n_de_un_proyecto) paso 4
Falta capitalizar el inicio de la oración
![Screen Shot 2020-08-05 at 12 03 11 PM](https://user-images.githubusercontent.com/5700527/89442118-dff5cd80-d713-11ea-9aac-be2b71555ba8.png)

##### [Sección 2.2.5.](http://mb.gbif.org/documents/doc-openrefine-guide/es/#_n%C3%BAmero_de_elecciones_l%C3%ADmite_en_las_facetas) 
Cambiar la palabra _elecciones_ por _opciones_ para mayor consistencia con la terminología de Open Refine en los pantallazos

**Comment by pzermoglio** [comment]
Gracias @camiplata !!

- Sección 1 paso 2: agregada mención a tags. Además, reestructuración de sección 1, agregada nueva sección sobre [metadatos de proyecto](https://docs.gbif-uat.org/openrefine-guide/1.0/es/#abrir-un-proyecto-y-modificar-sus-metadatos).
- Sección 1 paso 4: corregido.
- Sección 2.2.5: de acuerdo. Modificado también considerando comentario de @bienflorencia (ver https://github.com/gbif/doc-openrefine-guide/issues/20), a:
"Límite en el número de opciones de las Facetas".

**Comment by pzermoglio** [comment]
All topics addressed, closing this issue.
