### ISSUE TITLE
OpenRefine 3.3

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#27]
Should the revision be based on the latest version of OpenRefine? The current production version is  3.3 (https://github.com/OpenRefine/OpenRefine/releases/tag/3.3). Version 3.3 added a menu option for concatenating columns...

![image](https://user-images.githubusercontent.com/462827/90432279-ae301f80-e0a0-11ea-9fe7-8b52f94bcb5c.png)

![image](https://user-images.githubusercontent.com/462827/90432342-c43de000-e0a0-11ea-9795-5ece6e1f9a31.png)

This would affect Figure 7, Figure 10, Figure 28, Figure 43 for the Edit column menu. It would also greatly affect section 2.1.3, making that section much easier for users.

Version 3.4 beta2 (https://github.com/OpenRefine/OpenRefine/releases/tag/3.4-beta2) 

- offers a Windows package with embedded Java runtime engine (no need to install Java with this one)
- has a lot of Google Sheet integration, including exports to
- has an option in the CSV/TSV importer to strip whitespace in cell values

Any version change would affect:
- Prefacio/Software
- Figura 1
- Figura 2
- Figura 3
- Figura 4
- Instalación en MS Windows/ kit de windows link
- versión para Linux link

**Comment by pzermoglio** [comment]
We have updated the Guide to version 3.3. Currently OpenRefine goes up to version 3.4.1, but some issues have been encountered with it regarding memory. We've decided then to go up to 3.3. 

The "Join columns" function has now been incorporated in this revision, with added figure (all other figure numbers updated) and new example tables, under section "Manejo básico de columnas".
