### ISSUE TITLE
Figuras 2 & 3 Idioma

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#29]
When installing OpenRefine for the very first time, the interface will be in English, unlike in Figura 2 or Figura 3. One solution would be to mention that fact and keep the Figures in Spanish. Another would be to change the figures to English and add an extra one that shows what the interface will look like in Spanish every other time OpenRefine is opened thereafter until a new language is chosen.

**Comment by MattBlissett** [comment]
If the browser is set to Spanish (either because the computer's OS is set to Spanish, or because the user has specifically set the browser to Spanish) then OpenRefine detects this, and presents that initial screen in Spanish.

**Comment by tucotuco** [comment]
Excellent. Then we can disregard my concern altogether. Thanks @MattBlissett
