### ISSUE TITLE
Title proposal

### ISSUE THREAD

**Issue by camiplata** [gbif/doc-openrefine-guide#30]
@pzermoglio what do you think about removing the  word "Básico"  from the title, I believe, even in its v1.0 the guide is very complete and explains also advanced topics.

**Comment by pzermoglio** [comment]
[original title was: "Guía de Uso Básico de OpenRefine para la limpieza de datos sobre biodiversidad"

Agreed to take out "Básico".

In conversations we've come to the conclusion that the title should probably change a little more, and came up with the following final title proposal:

ES: **Guía para la limpieza de datos sobre biodiversidad con OpenRefine**
EN: **Guide for biodiversity data cleaning with OpenRefine**

These:
a) are shorter,
b) keep "guide" in, which 
  - may be good as people may remember the document just as "the OR Guide"
  - the doc is indeed a guide, with steps and such.

and c) translation to EN has a more similar structure / look to each other (than the original title would to the translated version).

@kcopas thumbs up for this change?

(I've changed the title everywhere were it was used, but can change back if you don't agree of course)

**Comment by kcopas** [comment]
Yes, sounds great—I trust you all to know best on this, but thank you for the heads-up!

**Comment by pzermoglio** [comment]
Great, thanks @kcopas!
Closing this issue then.
