### ISSUE TITLE
GEOLocate API Image shows Tulane URL

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#33]
The associated text is updated, but the associated image has the out of date web service URL.

**Comment by MattBlissett** [comment]
See #16, although it is probably easier to ignore the PR but just pull out the screenshots: https://github.com/gbif/doc-openrefine-guide/blob/geo-locate-service/img/es.figure-46.png and https://github.com/gbif/doc-openrefine-guide/blob/geo-locate-service/img/es.figure-46.png

**Comment by pzermoglio** [comment]
Fixed!
Closing issue.
