### ISSUE TITLE
Update publication year for final version?

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#35]
Found in "Cita bibliográfica sugerida" and "Control de documentos".

**Comment by tucotuco** [comment]
While at it, update in "Control de documentos" - "Este documento se basa en una publicación anterior de la guía por los mismos autores." It's now a amalgamation of two previous works.

**Comment by pzermoglio** [comment]
Fixed "Este documento se basa en una publicación anterior de la guía por los mismos autores.". Now reads:
"Este documento se basa en dos publicaciones anteriores producidas por los mismos autores de esta Guía."

Fixed year in the citation.

For year in Control de Documentos, it says:
=== Control de documentos
Versión 3, edición de revisión comunitaria, Marzo 2020.

Not sure if that should be changed, as the review was not in 2021 but in 2020. @kcopas ?

**Comment by tucotuco** [comment]
But the published version will be a post-revision version finished in 2021,
no?

**Comment by kcopas** [comment]
«Versión 3, Febrario 2021» I'd suggest, if I understand how we've gotten here properly. The community review edition is more like a qualification on v3 than a version outright. The current update/overhaul came out of that process, so this should be the "full" version 3 imho.

**Comment by tucotuco** [comment]
Sounds right.

**Comment by pzermoglio** [comment]
Thanks!
Fixed.
