### ISSUE TITLE
Omit "basic" from Prefacio, Objetivo

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#36]
Currently, it says, "La presente guía ha sido construida con fines únicamente pedagógicos. El objetivo de esta guía es mostrar cómo utilizar algunas de las funciones básicas de OpenRefine que pueden utilizarse para evaluar y mejorar la calidad de datos de biodiversidad."

Suggest, "La presente guía ha sido construida con fines únicamente pedagógicos. El objetivo de esta guía es mostrar cómo utilizar algunas de las funciones de OpenRefine que pueden utilizarse para evaluar y mejorar la calidad de datos de biodiversidad."

**Comment by pzermoglio** [comment]
Changed.
