### ISSUE TITLE
Changes for Section "Cómo usar esta guía"

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#37]
Omit básicas from "En esta guía se muestra cómo utilizar funciones básicas de OpenRefine para la evaluación y mejoramiento de la calidad de un conjunto de datos de biodiversidad."

Omit repeated "se utiliza" from "En el texto se utiliza se utiliza el siguiente formato para los "nombres de los campos originales".

**Comment by pzermoglio** [comment]
Changes incorporated.
