### ISSUE TITLE
Changes for Section "Software"

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#38]
Suggest "Aunque no es la última versión disponible, es la última con que todos los pasos estaban probados sin presentar problemas." 

in place of

"Aunque la última versión disponible es la 3.4.1, esta ha presentado algunos problemas de memoria y por lo tanto no se aborda en esta guía.".

**Comment by pzermoglio** [comment]
Fixed to:
"Aunque no es la última versión disponible, es la última con la cual todos los pasos explicados en esta Guía han sido probados sin presentar problemas."
