### ISSUE TITLE
Changes for Section "Datos"

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#39]
The linked text for the data says "EjercicioModelo_OpenRefine_Datos.csv", but the actual file is EjercicioModelo_OpenRefine_Datos.zip. Suggest making the file match link to avoid having user problems unzipping and having to change the accompanying explanation.

Suggest "El conjunto de datos modelo fue derivado a partir del conjunto de datos:"

in place of

"El conjunto de datos modelo fue derivado a partir de:".

**Comment by tucotuco** [comment]
Oops.

Suggest "El conjunto de datos modelo fue derivado a partir de:".

in place of

"El conjunto de datos modelo fue derivado a partir del conjunto de datos:"

**Comment by pzermoglio** [comment]
All changes adopted.
