### ISSUE TITLE
Changes for Section "Paso 2"

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#40]
Suggest "Allí puede encontrar dos cuadros de texto arriba a la derecha,"

in place of 

"Allí puede ncontrar dos cuadros de texto arriba a la derecha,".

Suggest "modificar varios aspectos de la carga de los datos al programa: codificación, criterio para la separación en columnas, inclusión o no de las primeras filas, etc."

in place of

"modificar varios aspectos de la carga de los datos al programa: codificación, criterio para la separación en columnas, inclusión o no de la primera fila, etc."

**Comment by pzermoglio** [comment]
Both corrected.
