### ISSUE TITLE
Changes for Section "1.2 Abrir un proyecto y modificar sus metadatos"

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#41]
The link for Figura 3 should be to "https://docs.gbif-uat.org/openrefine-guide/1.0/es/#img-fig-03" rather than "https://docs.gbif-uat.org/openrefine-guide/1.0/es/#img-fig-3".

The links (2 of them) for Figura 7a should be to "https://docs.gbif-uat.org/openrefine-guide/1.0/es/#img-fig-07" rather than "https://docs.gbif-uat.org/openrefine-guide/1.0/es/#img-fig-7".

The link for Figura 7b should be to "https://docs.gbif-uat.org/openrefine-guide/1.0/es/#img-fig-07" rather than "https://docs.gbif-uat.org/openrefine-guide/1.0/es/#img-fig-7".

**Comment by pzermoglio** [comment]
All corrected.
