### ISSUE TITLE
Changes for Section "2.1.3 Nuevas columnas a partir transformaciones simples de otras columnas"

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#42]
In the paragraph that begins "La fórmula anterior (Expresión 2) resuelve el problema", suggest

"Por ejemplo, si el valor de "genus" es nulo, el valor resultante en el campo concatenado será " epíteto", con un espacio en blanco antes del epíteto; si el valor de "specificEpithet" es nulo, el valor resultante será "genus ", con un espacio en blanco después del género; y si los valores de ambos campos son nulos, el valor resultante será " ", un espacio en blanco"

in place of 

"Por ejemplo, si "genus" es nulo, el valor resultante en el campo concatenado será " epíteto", con un espacio en blanco antes del epíteto; si "specificEpithet" es nulo, el valor resultante será "genus ", con un espacio en blanco después del género; y si ambos son campos son nulos, el valor resultante será " ", un espacio en blanco".

Suggest "Tabla 2. Ejemplos de concatenación de dos columnas (“genus” y “specificEpithet”) en otra (“concat_scientificName), utilizando distintas expresiones (ver texto más arriba)"

in place of

"Tabla 2. Ejemplos de concatenación de dos columnas (“genus” y “specificEpithet”) en otra (“concat_scientificName), utilizando distintos distintas expresiones (ver texto más arriba)".

Suggest "Se abrirá una nueva ventana (Figura 13). Allí debe escoger si se dividirá por separador o por longitud de caracteres, y en el primer caso qué tipo de separador se utilizará (puede ser espacio, carácter de tabulación, coma, punto y coma, guión, etc.)"

in place of 

"Se abrirá una nueva ventana (Figura 13). Allí debe escoger si se dividirá por separador o por longitud de caracteres, y en el primer caso qué tipo de separador se utilizará (puede ser espacio –tab-, coma, punto y coma, guión, etc.)".

**Comment by pzermoglio** [comment]
All changes incorporated.
