### ISSUE TITLE
Changes for Section "2.3.2 Filtros con expresiones regulares"

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#43]
Throughout the section, I suggest replacing "caracter" with "carácter".

In the explanation for ^\w I suggest 

"Busca las cadenas de texto **alfanuméricas** que comienzan (^) con un **número o** una letra (\w) –de **0 a 9 o** de la a a la z, mayúscula o minúscula **, o el carácter '_'**."

in place of 

"Busca las cadenas de texto que comienzan (^) con un una letra (\w) –de la a a la z, mayúscula o minúscula."

In the explanation for ^\w.*\d$ I suggest 

"Busca las cadenas de texto que comiencen (^) con **un carácter alfanumérico o el carácter '_'**  (\w), sigan (.) cualquier **carácter** (*) y terminen ($) con un dígito (\d)."

in place of

"Busca las cadenas de texto que comiencen (^) con una letra (\w), sigan (.) cualquier caracter (*) y terminen ($) con un dígito (\d)."

It might be worth adding the following expression as well:

"[A-Za-zÀ-ÖØ-öø-ÿ]
Busca cadenas de texto que contengan por lo menos un carácter con acento ([A-Za-zÀ-ÖØ-öø-ÿ]) –dentro de los rangos de caracteres Unicode A-Z o a-z o À-Ö o Ø-ö o ø-ÿ."

**Comment by pzermoglio** [comment]
All corrected / added.

The suggested new expression did not match the description suggested, changed to:

[À-ÖØ-öø-ÿ]
Busca las cadenas de texto que contengan al menos un carácter especial ([À-ÖØ-öø-ÿ]) –dentro de los rangos de caracteres Unicode À-Ö o Ø-ö o ø-ÿ, por ejemplo caracteres con diacríticos (acentos graves, agudos, circunflejos, diéresis, virguillas, cedilla, etc.)
