### ISSUE TITLE
Changes for "Section 4.1 Resolución de nombres científicos usando Global Names Resolver"

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#44]
Below Figura 49, suggest 

"Una vez que haya creado el campo, verá que contiene los valores de interés extraídos de GNR **separados por' | '**."

in place of

"Una vez que haya creado el campo, verá que contiene **, aún en formato JSON,** los valores de interés extraídos de GNR."

**Comment by pzermoglio** [comment]
Changed.
