### ISSUE TITLE
Changes for Section "4.2 Georreferenciación usando GEOLocate"

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-openrefine-guide#45]
Below Método 2, the formula has a trailing .join("|") that doesn't do anything. For a cleaner formula, suggest

`forEach(filter(value.parseJson().resultSet.features, v, isNonBlank(v.geometry)), w, w.geometry.coordinates[0]).join("; "))`

in place of 

`forEach(filter(value.parseJson().resultSet.features, v, isNonBlank(v.geometry)), w, w.geometry.coordinates[0]).join("; ")).join("|")`

**Comment by pzermoglio** [comment]
Changed.
