### ISSUE TITLE
Confirm author ORCID IDs

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-openrefine-guide#46]
Want to make sure that we get these identifiers right.

+ Camila Andrea Plata: https://orcid.org/0000-0002-1632-9818
    + @camiplata what is your preference—the above or Camila Andrea Plata Corredor?
+ Ricardo Ortíz, or Ortíz Gallego? Can't find an ORCID, which is fine, but if there is one…   
+ Leonardo Buitrago: https://orcid.org/0000-0002-0459-4024

Cc @pzermoglio @tucotuco

**Comment by pzermoglio** [comment]
Leo confirmed that his ORCID is correct.

Ricardo's is: [https://orcid.org/0000-0003-1070-1081](https://orcid.org/0000-0003-1070-1081) (confirmed by him). But we should put him as Ricardo Ortiz Gallego. 

Updated Ricardo's surname and added those ORCIDs in Colophon.

**Comment by camiplata** [comment]
I just updated my info, ORCID ( https://orcid.org/0000-0002-1632-9818) and name at the Colophon.
