### ISSUE TITLE
Is date formatting ok in §4.1.3?

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-openrefine-guide#6]
@pzermoglio is it a problem that we don't have bold red text for the 'T' and 'X' in your call-out of AAAA-MM-DDTHH:mmX of §4.1.3?
https://docs.gbif-uat.org/openrefine-guide/1.0/es/#_breve_introducción

Fwiw, I personality don't think it's missed in the online version.

**Comment by pzermoglio** [comment]
@kcopas 
In this particular case, it is not a big issue, since the rest of the expression is pretty simple to follow.
