### ISSUE TITLE
Choose cover image

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-openrefine-guide#7]
Cover images for GBIF guides should come from the [40 million+ occurrence photos](https://www.gbif.org/occurrence/gallery) available on GBIF.org. 

In future, the Secretariat may reserve the right to choose the photo (O'Reilly authors don't get to pick!), but for this inaugural doc, and in recognition of the central role she and @tucotuco have played in this project, I'd really like input from @pzermoglio. 

My first naïve pass included some Argentinian options:
+ [_Lama guanicoe_](https://www.gbif.org/occurrence/2005372769)
+ [_Cyttaria hariotii_](https://www.gbif.org/occurrence/1990514294) (h/t @tucotuco)
+ [_Chaetophractus villosus_](https://www.gbif.org/occurrence/1986623996)
+ [_Alouatta caraya_](https://www.gbif.org/occurrence/1993743895)
+ [_Lycalopex gymnocercus_](https://www.gbif.org/occurrence/1993744013)

Other suggestions are most welcome.

**Comment by kcopas** [comment]
Garbage draft of the cover [here](https://github.com/gbif/doc-openrefine-guide/files/3152167/cover_v0.pdf)…

**Comment by kcopas** [comment]
Thanks, Paula—that Guias de Datos is very much an artefact of the creative process here! 

I expect to build a little more texture into the cover as well, but after today's call, I'm ready to think that the overall series should be called the 'Data Skills Guides.' It would be good to know if that's something that could carry a similar, positive connotation in Spanish translation.

**Comment by pzermoglio** [comment]
Thanks @kcopas!
I like that draft cover!
Not sure about "Guias de Datos" at the bottom, though, not sure what it would refer to...

**Comment by kcopas** [comment]
@pzermoglio would 'Data Skills Guides' translate to something like 'Guías de habilidades de datos'?

If so, with or without caps, when used as a series name?

**Comment by pzermoglio** [comment]
@kcopas 
Hmm... that IS the translation... but it does sound a bit weird...like, not 'natural'... not clear what it would mean... I would go for "Guías de Habilidades con Datos", or better "**Guías de Habilidades para Trabajar con Datos**", as that would really be what it means. I'll ask others what they think, see if in other es-speaking countries there is a best way.

**Comment by pzermoglio** [comment]
@kcopas 
We need to remember to complete the part in the Colophon about the cover image (author, licence, etc).
