### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-openrefine-guide#8]
- In the Colofón, Suggested citation, it says “Tercera edición” (third edition). Why third edition and not V 3.0? Is there an agreement on how versions will be dealt with?

- Guide appears as version 1.0 (just under title in html version, cover page under authors in pdf version). However, it is not the first version of the guide, but version 3.0, as previous versions were –unofficially- released and used by many in courses and such. (As appears in the suggested citation (“Tercera edición”)). I guess this makes it here automatically. Could it be modified?

**Comment by MattBlissett** [comment]
The URL and the line under the title are automatically set (in two different places) from the Git branch name, which is currently `1.0`.

**Comment by kcopas** [comment]
Whether now or after the community review, we can set the version number to three, if you'd prefer @pzermoglio . 

Meanwhile, in terms of style, we'll follow O'Reilly and "[use numerals for versions (version 5 or v5)](http://oreillymedia.github.io/production-resources/styleguide/#dates_and_numbers).
