### ISSUE TITLE
Declaration of language

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-openrefine-guide#9]
In the Preface, there is a subsection, preliminary comments (Comentarios Preliminares) where it is declared that the text and images of this guide are all in Spanish.
Maybe this would not be necessary given the whole version is declared to be in ES...?

**Comment by MattBlissett** [comment]
I have changed with a conditional directive, so it only appears on non-Spanish documents:

```
ifeval::["{lang}" != "es"]
=== Comentarios Preliminares

El imágenes incluidos en esta guía están en idioma castellano.
endif::[]
```
